# Generated by Django 3.0.8 on 2020-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20200712_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_pic',
            field=models.ImageField(default='N/A', upload_to='seller'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='shop_owner_pic',
            field=models.ImageField(default='N/A', upload_to='shop'),
        ),
    ]
